some  concepts learnt

np.arange(n)==range of numbers upto n
similar to python built in range() function

twod_array=np.arange(9).reshape(3,3) making a range of numbers  upto 0 to 9 inclusive to a 3*3 cardinality matrix

np.zeros((3,4))
np.zeros((rows,cols))

Step size  in a matrix = how many elements to skip to move to the next position in memory.



np_5=np.arange(10,50,5)
which will increment with 5


linspace() divides the range evely by calculating the stepsize


In [ ]:
# NumPy Fundamentals - Student Lab
'''
## Lab Instructions

Complete all exercises below. Write your code in a Python file or Jupyter notebook. Test each task to ensure it produces the expected output.

**Assessment Criteria:**
- Code correctness and functionality
- Proper use of NumPy functions
- Code efficiency (use vectorized operations)
- Clean, readable code with appropriate comments

---

## Exercise 1: Array Creation and Attributes (15 points)

### Task 1.1: Create arrays using different methods (10 points)

Write code to create the following arrays:

1. A 1D array containing values from 0 to 9
2. A 2D array (3x3) containing values from 1 to 9
3. A 3x4 array filled with zeros
4. A 2x5 array filled with ones (data type: float32)
5. A 4x4 identity matrix
6. An array with values from 10 to 50 with step size 5
7. An array with 8 evenly spaced values between 0 and 1

**Your Code:**
```python
import numpy as np

# Write your code here
# '''

# Write code to create the following arrays:
import numpy as np

print("# 1. A 1D array containing values from 0 to 9")
oned_array_upto9=np.arange(10)
print(oned_array_upto9)
print("# 2. A 2D array (3x3) containing values from 1 to 9")
twod_array=np.arange(1,10).reshape(3,3)
print(twod_array)
li =range(1,10)
print("genrated using list conversion")
other_way_2d=np.array(li).reshape(3,3)
print(other_way_2d)
print("# 3. A 3x4 array filled with zeros")
zero_array=np.zeros((3,4))
print(zero_array)
print("# 4. A 2x5 array filled with ones (data type: float32)")
print("Generating using float32 ")
ones_arr=np.ones((2,5),dtype='float32')
print(ones_arr)
print("if i use only float")
ones_arr=np.ones((2,5),dtype='float64')
print(ones_arr)
print("# 5. A 4x4 identity matrix")
#four_identity=np.ones((4,4),dtype='int')
four_identity=np.eye(4,dtype=int)
print(four_identity)
print("# 6. An array with values from 10 to 50 with step size 5")
array_5=np.arange(10,50,5)
print(array_5)
print("7. An array with 8 evenly spaced values between 0 and 1")
array_8=np.linspace(0,1,8)
print(array_8)



# 1. A 1D array containing values from 0 to 9
[0 1 2 3 4 5 6 7 8 9]
# 2. A 2D array (3x3) containing values from 1 to 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
genrated using list conversion
[[1 2 3]
 [4 5 6]
 [7 8 9]]
# 3. A 3x4 array filled with zeros
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
# 4. A 2x5 array filled with ones (data type: float32)
Generating using float32 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
if i use only float
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
# 5. A 4x4 identity matrix
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
# 6. An array with values from 10 to 50 with step size 5
[10 15 20 25 30 35 40 45]
7. An array with 8 evenly spaced values between 0 and 1
[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.        ]


In [ ]:
'''
### Task 1.2: Explore array attributes (5 points)

Create a 3x4 array with values from 1 to 12. Print the following attributes:
- Shape
- Number of dimensions
- Total number of elements
- Data type
- Item size in bytes
- Total bytes consumed

'''
import numpy as np
matrix_a=np.arange(1,13).reshape(3,4)

print("matrix a"+str(matrix_a))

print("Shape")
print(matrix_a.shape)
#print("means==  numpyvariable.shape=(3,4) meaning 3  rosw, 4 columns defined.")
print("Number of dimensions")
print(matrix_a.ndim)

print("Total number of elements")
print(matrix_a.size)
print("Data type")
print(matrix_a.dtype)
print("Item size in bytes")
print(matrix_a.itemsize)
print("Total bytes consumed")
print(matrix_a.nbytes)


matrix a[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape
(3, 4)
Number of dimensions
2
Total number of elements
12
Data type
int64
Item size in bytes
8
Total bytes consumed
96


In [ ]:

'''

## Exercise 2: Indexing and Slicing (20 points)

### Task 2.1: Basic indexing (5 points)

Given the array: `arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])`

Write code to:
1. Access the first element
2. Access the last element using negative indexing
3. Access the 5th element

Then create a 2D array with shape (3, 4) and:
- Access the element at row 1, column 2
- Access the element at row 0, column 3
- Access the last element
'''
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print("Access the first element")
print(arr[0])
print("Access the last element using negative indexing")
print(arr[-1])
print("Access the 5th element")
print(arr[4])

arr2=np.arange(1,13).reshape(3,4)
print(arr2)
print("Access the element at row 1, column 2")
print(arr2[1][2])
print("Access the element at row 0, column 3")
print(arr2[0][3])
print("Access the last element")
# wrong print(arr2[arr2.length][arr2[0].length])
print(arr2[arr2.shape[0]-1][arr2.shape[1]-1])

Access the first element
10
Access the last element using negative indexing
100
Access the 5th element
50
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Access the element at row 1, column 2
7
Access the element at row 0, column 3
4
Access the last element
12


In [ ]:
'''
### Task 2.2: Slicing operations (8 points)

Given `arr = np.arange(0, 20)`:

1. Extract elements from index 5 to 15 (inclusive)
2. Extract every 3rd element from the array
3. Reverse the entire array using slicing

Create a 4x4 2D array and:
- Extract the first 2 rows and first 3 columns
- Extract the last 2 rows and last 2 columns
- Extract every other row with all columns
'''
arr = np.arange(0, 20)
print(arr)
print("Extract elements from index 5 to 15 (inclusive)")
print(arr[5:16])
## arr[inclusive:exclusive]
print("Extract every 3rd element from the array")
print(arr[::3])
## from 0 skips 3 indexex
print("Reverse the entire array using slicing")
print(arr[::-1])
## using negative indexing
arr=np.arange(1,17).reshape(4,4)
print(arr)
print("Extract the first 2 rows and first 3 columns")
print(arr[:2,:3])
print("Extract the last 2 rows and last 2 columns")
print(arr[-2:,-2:])
print("Extract every other row with all columns")
print(arr[::2][:2])



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Extract elements from index 5 to 15 (inclusive)
[ 5  6  7  8  9 10 11 12 13 14 15]
Extract every 3rd element from the array
[ 0  3  6  9 12 15 18]
Reverse the entire array using slicing
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Extract the first 2 rows and first 3 columns
[[1 2 3]
 [5 6 7]]
Extract the last 2 rows and last 2 columns
[[11 12]
 [15 16]]
Extract every other row with all columns
[[ 1  2  3  4]
 [ 9 10 11 12]]


In [ ]:
'''
### Task 2.3: Boolean and fancy indexing (7 points)

Given `arr = np.array([15, 23, 8, 42, 11, 37, 19, 5, 33, 28])`:

1. Use boolean indexing to extract all values greater than 20
2. Extract all even numbers
3. Extract values between 10 and 30 (inclusive)
4. Use fancy indexing to extract elements at indices 0, 3, 5, and 8
'''
arr = np.array([15, 23, 8, 42, 11, 37, 19, 5, 33, 28])
print(arr)
print("Extract all values greater than 20")
print(arr[arr>20])
print("Extract all even numbers")
print(arr[arr%2==0])
print("Extract values between 10 and 30 (inclusive)")
print(arr[(arr>=10)&(arr<=30)])
print("Extract elements at indices 0, 3, 5, and 8")
print(arr[[0,3,5,8]])

[15 23  8 42 11 37 19  5 33 28]
Extract all values greater than 20
[23 42 37 33 28]
Extract all even numbers
[ 8 42 28]
Extract values between 10 and 30 (inclusive)
[15 23 11 19 28]
Extract elements at indices 0, 3, 5, and 8
[15 42 37 33]


In [ ]:
'''
## Exercise 3: Array Operations (15 points)

### Task 3.1: Arithmetic operations (8 points)

Given two arrays:
- `arr1 = np.array([10, 20, 30, 40, 50])`
- `arr2 = np.array([5, 10, 15, 20, 25])`

Perform the following operations:
1. Element-wise addition
2. Element-wise subtraction
3. Element-wise multiplication
4. Element-wise division
5. Square each element of arr1

Then perform scalar operations on arr1:
- Add 100 to all elements
- Multiply all elements by 3
- Divide all elements by 10
'''
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([5, 10, 15, 20, 25])
print(arr1)
print(arr2)
print("Element-wise addition")
print(arr1+arr2)
print("Element-wise subtraction")
print(arr1-arr2)
print("Element-wise multiplication")
print(arr1*arr2)
print("Element-wise division")
print(arr1/arr2)
print("Square each element of arr1")
## wrong print(arr1[arr1*arr1])
print(arr1**2)
print("Add 100 to all elements")
print(arr1+100)
print("Multiply all elements by 3")
print(arr1*3)
print("Divide all elements by 10")
print(arr1/10)


[10 20 30 40 50]
[ 5 10 15 20 25]
Element-wise addition
[15 30 45 60 75]
Element-wise subtraction
[ 5 10 15 20 25]
Element-wise multiplication
[  50  200  450  800 1250]
Element-wise division
[2. 2. 2. 2. 2.]
Square each element of arr1
[ 100  400  900 1600 2500]
Add 100 to all elements
[110 120 130 140 150]
Multiply all elements by 3
[ 30  60  90 120 150]
Divide all elements by 10
[1. 2. 3. 4. 5.]


In [ ]:
''''

### Task 3.2: Universal functions (7 points)

Given `arr = np.array([1, 4, 9, 16, 25, 36])`:

1. Calculate square root of all elements
2. Calculate exponential (e^x) of all elements
3. Calculate natural logarithm of all elements

Create an array of angles `[0, π/6, π/4, π/3, π/2]` and:
- Calculate sine values
- Calculate cosine values

For the array `[1.23, 2.56, 3.89, 4.12]`:
- Round to nearest integer
- Apply floor operation
- Apply ceiling operation
'''
arr = np.array([1, 4, 9, 16, 25, 36])
print(arr)
print("Calculate square root of all elements")
print(arr**(0.5))
print(np.sqrt(arr))
print("Calculate exponential (e^x) of all elements")
# x=2
# print(arr**x) it is not exponential
print(np.exp(arr))
print("Calculate natural logarithm of all elements")
print(np.log(arr))
pie=round(np.pi,2)
angles=[0, pie/6, pie/4, pie/3, pie/2]
print(angles)
print("Calculate sine values")
print(np.sin(angles))

print("Calculate cosine values")
print(np.cos(angles))
arr1=[1.23, 2.56, 3.89, 4.12]
print(arr1)
print("Round to nearest integer")
print(np.round(arr1))
print("Apply floor operation")
print(np.floor(arr1))
print("Apply ceiling operation")

print(np.ceil(arr1))
## round goes to nearest integer
#floor goes to bottom integer
# ceil goes to upward intteger

[ 1  4  9 16 25 36]
Calculate square root of all elements
[1. 2. 3. 4. 5. 6.]
[1. 2. 3. 4. 5. 6.]
Calculate exponential (e^x) of all elements
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]
Calculate natural logarithm of all elements
[0.         1.38629436 2.19722458 2.77258872 3.21887582 3.58351894]
[0, 0.5233333333333333, 0.785, 1.0466666666666666, 1.57]
Calculate sine values
[0.         0.4997701  0.70682518 0.86575984 0.99999968]
Calculate cosine values
[1.00000000e+00 8.66158094e-01 7.07388269e-01 5.00459689e-01
 7.96326711e-04]
[1.23, 2.56, 3.89, 4.12]
Round to nearest integer
[1. 3. 4. 4.]
Apply floor operation
[1. 2. 3. 4.]
Apply ceiling operation
[2. 3. 4. 5.]


In [ ]:
'''

## Exercise 4: Array Manipulation (20 points)

### Task 4.1: Reshaping and transposing (10 points)

Create an array with values from 1 to 12, then:
1. Reshape it to 3x4
2. Reshape it to 2x6
3. Reshape it to 2x2x3 (3D array)
4. Transpose the 3x4 array
5. Flatten the 3x4 array back to 1D
'''
arr=np.arange(1,13)
print(arr)
arr2=np.arange(1,13).reshape(3,4)
print("Reshape the array to 3x4")
print(arr.reshape(3,4))
print("Reshape the array to 2x6")
print(arr.reshape(2,6))
print("Reshape the array to 2x2x3 (3D array)")
print(arr.reshape(2,2,3))
print("Transpose the 3x4 array")
arr2=arr2.reshape(3,4).T
print(arr2)
print("Flatten the 3x4 array back to 1D")
print(arr2.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshape the array to 3x4
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshape the array to 2x6
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Reshape the array to 2x2x3 (3D array)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Transpose the 3x4 array
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
Flatten the 3x4 array back to 1D
[ 1  5  9  2  6 10  3  7 11  4  8 12]


In [ ]:
'''

### Task 4.2: Stacking and splitting (10 points)

Create three 1D arrays: `[1, 2, 3]`, `[4, 5, 6]`, `[7, 8, 9]`

1. Stack them vertically to create a 3x3 array
2. Stack them horizontally to create a 1D array

Create an array from 1 to 12 and:
- Split it into 4 equal parts

Create a 4x4 array with values 1-16 and:
- Split it horizontally into 2 parts
'''
import numpy as np
arr=[1, 2, 3]
arr2=[4, 5, 6]
arr3= [7, 8, 9]
print("Create three 1D arrays: [1,2,3], [4,5,6], [7,8,9]")


print(arr)
print(arr2)
print(arr3)
print("Stack them vertically to create a 3x3 array")

arr4=np.stack((arr,arr2,arr3))
print(arr4)
print("Stack them horizontally to create a 1D array")
arr5=np.hstack((arr,arr2,arr3))
print(arr5)

print("Create an array from 1 to 12 and split it into 4 equal parts")
arr6=np.arange(1,13)
print(arr6)
print(np.split(arr6,4))
arr7=np.split(arr6,4)
print(arr7)
print("Create a 4x4 array with values 1 to 16 and split it horizontally into 2 parts")
arr8=np.arange(1,17).reshape(4,4)
print(np.hsplit(arr8,2))


Create three 1D arrays: [1,2,3], [4,5,6], [7,8,9]
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
Stack them vertically to create a 3x3 array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Stack them horizontally to create a 1D array
[1 2 3 4 5 6 7 8 9]
Create an array from 1 to 12 and split it into 4 equal parts
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]
Create a 4x4 array with values 1 to 16 and split it horizontally into 2 parts
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]


In [ ]:
'''
## Exercise 5: Statistical Operations (15 points)
### Task 5.1: Basic statistics (7 points)
Given `arr = np.array([12, 45, 23, 67, 34, 89, 56, 78, 90, 31])`:
Calculate and print:
1. Sum of all elements
2. Mean (average)
3. Median
4. Standard deviation
5. Variance
6. Minimum value
7. Maximum value
8. Index of minimum value
9. Index of maximum value
'''
arr = np.array([12,45,23,67,34,89,56,78,90,31])
print(arr)
print("1. Sum of all elements")
print(arr.sum())
print("2. Mean (average)")
print(arr.mean())
print("3. Median")
print(np.median(arr))
# print(arr.median())
print("4. Standard deviation")
print(arr.std())
print("5. Variance")
print(arr.var())
print("6. Minimum value")
print(arr.min())
print("7. Maximum value")
print(arr.max())
print("8. Index of minimum value")
print(arr.argmin())
print("9. Index of maximum value")
print(arr.argmax())

[12 45 23 67 34 89 56 78 90 31]
1. Sum of all elements
525
2. Mean (average)
52.5
3. Median
50.5
4. Standard deviation
26.424420523447623
5. Variance
698.25
6. Minimum value
12
7. Maximum value
90
8. Index of minimum value
0
9. Index of maximum value
8


In [ ]:
'''
### Task 5.2: Axis-based statistics (8 points)
Create a 3x3 array:
```
[[10, 20, 30],
 [40, 50, 60],
 [70, 80, 90]]
```
Calculate:
1. Sum of all elements
2. Sum along axis 0 (column-wise sum)
3. Sum along axis 1 (row-wise sum)
4. Mean along axis 0
5. Mean along axis 1
6. Maximum values along axis 0
7. Maximum values along axis 1
'''
a=np.arange(10,100,10).reshape(3,3)
print(a)
print("1. Sum of all elements")
print(a.sum())
print("2. Sum along axis 0 (column-wise sum)")
print(a.sum(axis=0))
print("3. Sum along axis 1 (row-wise sum)")
print(a.sum(axis=1))
print("4. Mean along axis 0")
print(a.mean(axis=0))
print("5. Mean along axis 1")
print(a.mean(axis=1))
print("6. Maximum values along axis 0")
print(a.max(axis=0))
print("7. Maximum values along axis 1")

print(a.max(axis=1))


[[10 20 30]
 [40 50 60]
 [70 80 90]]
1. Sum of all elements
450
2. Sum along axis 0 (column-wise sum)
[120 150 180]
3. Sum along axis 1 (row-wise sum)
[ 60 150 240]
4. Mean along axis 0
[40. 50. 60.]
5. Mean along axis 1
[20. 50. 80.]
6. Maximum values along axis 0
[70 80 90]
7. Maximum values along axis 1
[30 60 90]


In [ ]:
'''
## Exercise 6: Real-World Application - Student Grade Analysis (25 points)

You are given grade data for 5 students across 4 subjects (Math, Science, English, History):

```python
grades = np.array([
    [85, 90, 78, 88],
    [92, 88, 95, 90],
    [76, 82, 80, 75],
    [88, 85, 90, 92],
    [95, 92, 88, 94]
])
```

**Tasks:**

1. **Calculate the average grade for each student** (5 points)
   - Output should show Student 1: X.XX, Student 2: Y.YY, etc.

2. **Calculate the average grade for each subject** (5 points)
   - Output: Math: X.XX, Science: Y.YY, etc.

3. **Find the highest and lowest grades in each subject** (5 points)
   - Output for each subject: Highest = X, Lowest = Y

4. **Identify students with an average grade above 85** (3 points)
   - Print student number and their average

5. **Calculate the overall class average** (2 points)
   - Average of all grades across all students

6. **Normalize all grades to a scale of 0-10** (5 points)
   - Use min-max normalization formula: (value - min) / (max - min) * 10
   - Print the normalized grades array

**Bonus:** Identify the top-performing student (+2 points)

**Expected Output Format:**
```
--- Task 1: Student Averages ---
Student 1: XX.XX
...

--- Task 2: Subject Averages ---
Math: XX.XX
...

(Continue for all tasks)
```

'''
import numpy as np
grades = np.array([
    [85, 90, 78, 88],
    [92, 88, 95, 90],
    [76, 82, 80, 75],
    [88, 85, 90, 92],
    [95, 92, 88, 94]
])

print("Task 1: Student Averages")
print("Student 1")
avg1=grades[0].mean()
print(avg1)
print("Student 2")
avg2= grades[1].mean()
print(avg2)
print("Student 3")

avg3= grades[2].mean()
print(avg3)
print("Student 4")
avg4=grades[3].mean()
print(avg4)
print("Student 5")
avg5=grades[4].mean()
print(avg5)

#or in other way
n=1
for i in grades:
    print(f"Student {n}: {i.mean()}")
    n+=1
print()
print("Task 2: Subject Averages")
print("Math")
print("Subject grades of 5 studnets")
#print(grades[:,0])
print(grades[:,0])

print("Average")
#print(round(grades[:,0].mean(),2))
print("%.2f" % grades[:,0].mean())
print("Science")
print("Subject grades of 5 studnets")
#print(grades[:,1])
print(grades[:,1])
print("Average")
#print(round(grades[:,0].mean(),2))
print("%.2f" % grades[:,1].mean())
print("English")
print("Subject grades of 5 studnets")
print(grades[:,2])
print("Average")
print("%.2f" % grades[:,2].mean())
print("History")
print("Subject grades of 5 studnets")
print(grades[:,3])
print("Average")
print("%.2f" % grades[:,3].mean())

print()
print("Task 3: Subject High & Low")
print("Math Highest and Lowest")
print(grades[:,0].max(),end="  ")
print(grades[:,0].min())

print("Science Highest and Lowest")
print(grades[:,1].max(),end="  ")
print(grades[:,1].min())

print("English Highest and Lowest")
print(grades[:,2].max(),end="  ")
print(grades[:,2].min())
print("History Highest and Lowest")
print(grades[:,3].max(),end="  ")
print(grades[:,3].min())

s=["Math   ","Science","English","History"]
i=0
for i in range(4):
    print(s[i],"Highest:",grades[:,i].max()," Lowest: ",grades[:,i].min())

print()
print("Task 4: Students Above 85")
print("Students")
#print(grades[grades>85])
for i in range(len(grades)):
   avg=grades[i].mean()
   if avg>85:
      print("Student",i+1,":",round(avg,2))
print()
print("Task 5: Overall Class Average")
print("Class Average")
print(round(grades.mean(),2))

print()
print("Task 6: Normalized Grades (0-10)")

print("Normalized Grades")
mn=grades.min()
mx=grades.max()
norm=(grades-mn)/(mx-mn)*10
print(norm.round(2))


print()
print("Bonus: Top Performing Student")
print("Top Student")
avg=grades.mean(axis=1)
top=avg.argmax()
print("Student",top+1)

Task 1: Student Averages
Student 1
85.25
Student 2
91.25
Student 3
78.25
Student 4
88.75
Student 5
92.25
Student 1: 85.25
Student 2: 91.25
Student 3: 78.25
Student 4: 88.75
Student 5: 92.25

Task 2: Subject Averages
Math
Subject grades of 5 studnets
[85 92 76 88 95]
Average
87.20
Science
Subject grades of 5 studnets
[90 88 82 85 92]
Average
87.40
English
Subject grades of 5 studnets
[78 95 80 90 88]
Average
86.20
History
Subject grades of 5 studnets
[88 90 75 92 94]
Average
87.80

Task 3: Subject High & Low
Math Highest and Lowest
95  76
Science Highest and Lowest
92  82
English Highest and Lowest
95  78
History Highest and Lowest
94  75
Math    Highest: 95  Lowest:  76
Science Highest: 92  Lowest:  82
English Highest: 95  Lowest:  78
History Highest: 94  Lowest:  75

Task 4: Students Above 85
Students
Student 1 : 85.25
Student 2 : 91.25
Student 4 : 88.75
Student 5 : 92.25

Task 5: Overall Class Average
Class Average
87.15

Task 6: Normalized Grades (0-10)
Normalized Grades
[[ 5.   7.5

In [ ]:
'''
## Exercise 7: Challenge - Sales Data Analysis (30 points)

You are analyzing sales data for a company with 4 products over 6 months:

```python
sales_data = np.array([
    [120, 135, 150, 145, 160, 175],  # Product A
    [90, 95, 100, 110, 115, 120],    # Product B
    [150, 145, 155, 160, 170, 180],  # Product C
    [80, 85, 82, 88, 92, 95]         # Product D
])
```

**Tasks:**

1. **Calculate total sales for each product** (5 points)
   - Sum across all months for each product

2. **Calculate total sales for each month** (5 points)
   - Sum across all products for each month (Jan to Jun)

3. **Identify the month with the highest total sales** (4 points)
   - Print the month name and total sales

4. **Calculate the growth rate for each product** (6 points)
   - Growth rate = ((Last month - First month) / First month) × 100
   - Print as percentage for each product

5. **Find products with average monthly sales greater than 120k** (4 points)
   - Calculate average for each product
   - Print products meeting the criteria

6. **Calculate quarter-wise sales** (6 points)
   - Q1: January-March
   - Q2: April-June
   - Print sales for each product in each quarter

**Bonus:** Predict next month (July) sales for each product (+5 points)
- Use a simple method: average of last 2 months + average monthly growth

import numpy as np

sales_data = np.array([
    [120, 135, 150, 145, 160, 175],
    [90, 95, 100, 110, 115, 120],
    [150, 145, 155, 160, 170, 180],
    [80, 85, 82, 88, 92, 95]
])
'''
import numpy as np

sales_data = np.array([
    [120, 135, 150, 145, 160, 175],
    [90, 95, 100, 110, 115, 120],
    [150, 145, 155, 160, 170, 180],
    [80, 85, 82, 88, 92, 95]
])
print("Task 1: Total sales for each product")
for i in range(sales_data.shape[0]):
    print("Product",chr(65+i),":",sales_data[i].sum())
print("Task 2: Total sales for each month")
months=["January","February","March","April","May","June"]

for i in range(sales_data.shape[1]):
    print("Month ",(i+1),months[i],":",sales_data[:,i].sum())
print("Task 3: Month with highest total sales")

every_m_totals=sales_data.sum(axis=0)
maxi=every_m_totals.argmax()
print(months[maxi])
print("Month",maxi+1,":",every_m_totals[maxi])
print("Task 4: Growth rate for each product")
#Growth rate = ((Last month - First month) / First month) × 100

for i in range(sales_data.shape[0]):
    growth=((sales_data[i][-1]-sales_data[i][0]) / sales_data[i][0]) * 100
    print("Product",chr(65+i),":",round(growth,2),"%")

print("Task 5: Products with average monthly sales greater than 120k")
for i in range(sales_data.shape[0]):
    avg=sales_data[i].mean()
    if avg>120:
      print("Sales of product",chr(65+i),"with avg",avg)
print("Task 6: Quarter-wise sales")

print("Q1: January–March")
for i in range(sales_data.shape[0]):
    q1=sales_data[i][0]+sales_data[i][1]+sales_data[i][2]
    print("Product",chr(65+i),":",q1)
print("Q2: April–June")
for i in range(sales_data.shape[0]):
    q2=sales_data[i][3]+sales_data[i][4]+sales_data[i][5]
    print("Product",chr(65+i),":",q2)

print("Bonus: Predict next month (July) sales for each product")
print("We use growth rate by comparing first and last month sales and last 2 months average")
for i in range(sales_data.shape[0]):
    last2_avg=(sales_data[i][4]+sales_data[i][5])/2
    growth=(sales_data[i][5]-sales_data[i][0])/sales_data[i][0]
    july=last2_avg+(last2_avg*growth)
    print("Product",chr(65+i),":",round(july,2))


Task 1: Total sales for each product
Product A : 885
Product B : 630
Product C : 960
Product D : 522
Task 2: Total sales for each month
Month  1 January : 440
Month  2 February : 460
Month  3 March : 487
Month  4 April : 503
Month  5 May : 537
Month  6 June : 570
Task 3: Month with highest total sales
June
Month 6 : 570
Task 4: Growth rate for each product
Product A : 45.83 %
Product B : 33.33 %
Product C : 20.0 %
Product D : 18.75 %
Task 5: Products with average monthly sales greater than 120k
Sales of product A with avg 147.5
Sales of product C with avg 160.0
Task 6: Quarter-wise sales
Q1: January–March
Product A : 405
Product B : 285
Product C : 450
Product D : 247
Q2: April–June
Product A : 480
Product B : 345
Product C : 510
Product D : 275
Bonus: Predict next month (July) sales for each product
We use growth rate by comparing first and last month sales and last 2 months average
Product A : 244.27
Product B : 156.67
Product C : 210.0
Product D : 111.03


In [ ]:


```

---

## Submission Guidelines

1. Complete all exercises in order
2. Test your code to ensure it runs without errors
3. Include comments explaining your logic for complex operations
4. Format your output clearly with appropriate labels
5. Save your file as `numpy_lab_yourname.py` or `numpy_lab_yourname.ipynb`

---

## Evaluation Rubric

| Exercise | Points | Criteria |
|----------|--------|----------|
| Exercise 1 | 15 | Array creation and attributes |
| Exercise 2 | 20 | Indexing and slicing techniques |
| Exercise 3 | 15 | Array operations and ufuncs |
| Exercise 4 | 20 | Array manipulation |
| Exercise 5 | 15 | Statistical operations |
| Exercise 6 | 25 | Real-world application |
| Exercise 7 | 30 | Challenge problem |
| **Total** | **140** | |

**Bonus Points:** Up to +7 additional points available

**Grading Scale:**
- A: 126-140+ points (90%+)
- B: 112-125 points (80-89%)
- C: 98-111 points (70-79%)
- D: 84-97 points (60-69%)
- F: Below 84 points (Below 60%)

---

## Tips for Success

1. **Use vectorized operations** instead of loops whenever possible
2. **Understand the axis parameter**: axis=0 (down columns), axis=1 (across rows)
3. **Check array shapes** frequently to avoid dimension errors
4. **Use meaningful variable names** for clarity
5. **Test incrementally** - don't write all code at once
6. **Read NumPy documentation** when stuck: https://numpy.org/doc/

Good luck!